config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  resources :feeds, only: [:index]

  resources :entries, only: [:index] do
    collection do
      get :search
    end
  end

  root 'static#index'

  namespace :api, defaults: { format: 'json' } do
    resources :search, only: '' do
      collection do
        get :entries
        get :feeds
      end
    end
    resources :tokens, only: [:create] do
      collection do
        get :current
        post :refresh
      end
    end
    resources :feeds, only: %i[index show create] do
      collection do
        get :popular
      end
      resources :entries, only: %i[index show] do
        member do
          get :tags
        end
      end
      resources :logs, only: %i[index show]
      resources :webhooks
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-140621816-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-140621816-1');
    </script>
    <title>dato.rss</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Davide Santangelo">
    <meta name="description" content="dato.rss - RSS Search Engine - A search engine that allows you to find RSS feeds easily">
    <meta name="keywords" content="rails api web RSS">

    <meta property="og:type" content="website">
    <meta property="og:site_name" content="dato.rss - RSS Search Engine with RESTful API">
    <meta property="og:title" content="dato.rss - RSS Search Engine with RESTful API">
    <meta property="og:description" content="dato.rss - RSS Search Engine - A search engine that allows you to find RSS feeds easily">

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag "application", "data-turbo-track": 'reload' %>
    <%= favicon_pack_tag 'favicon.png' %>
  </head>

  <body class=" font-arial min-h-screen h-full bg-gray-100">
    <div class="px-8 py-2">
      <div class="my-4">
        <% if params[:controller] == 'feeds' %>
          <%= link_to 'dato.rss', root_path, class: 'inline-block align-middle py-2 text-xl underline text-green-600', title: 'back to homepage'%>
        <% end %>

        <% if params[:controller] == 'entries' %>
          <%= link_to 'feed.rss', feeds_path, class: 'inline-block align-middle py-2 text-xl underline text-blue-600', title: 'back to feeds' %>
        <% end %>
      </div>
        <%= form_tag search_entries_path, method: :get do %>
          <%= text_field_tag 'q', params[:q], class: 'border border-gray-400 py-3 px-3 text-grey-darkest w-full rounded', placeholder: 'what are you looking for?', type: 'search' %>
        <% end %>
      
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/static.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-140621816-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-140621816-1');
    </script>

    <title>dato.rss</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Davide Santangelo">
    <meta name="description" content="dato.rss - RSS Search Engine - A search engine that allows you to find RSS feeds easily">
    <meta name="keywords" content="rails api web RSS">

    <meta property="og:type" content="website">
    <meta property="og:site_name" content="dato.rss - RSS Search Engine with RESTful API">
    <meta property="og:title" content="dato.rss - RSS Search Engine with RESTful API">
    <meta property="og:description" content="dato.rss - RSS Search Engine - A search engine that allows you to find RSS feeds easily">

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "//cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css", media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= favicon_pack_tag 'favicon.png' %>

    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.js"></script>
    <!-- Place this tag in your head or just before your close body tag. -->
    <script async defer src="https://buttons.github.io/buttons.js"></script>
    <script>
      window.addEventListener("load", function () {
        window.cookieconsent.initialise({
          "palette": {
            "popup": {
              "background": "#252e39"
            },
            "button": {
              "background": "#14a7d0"
            }
          },
          "content": {
            "message": "We use cookies to help our site work and to understand how it is used. By continuing to browse the site you're agreeing to our use of cookies."
          }
        })
      });
    </script>
  </head>

  <body class="font-arial min-h-screen h-full">
    <%= yield %>
  </body>
</html>